INSERT INTO genre (genre_name) VALUES ('Art');
INSERT INTO genre (genre_name) VALUES ('Autobiography');
INSERT INTO genre (genre_name) VALUES ('Biography');
INSERT INTO genre (genre_name) VALUES ('Business');
INSERT INTO genre (genre_name) VALUES ('Childrens');
INSERT INTO genre (genre_name) VALUES ('Classics');
INSERT INTO genre (genre_name) VALUES ('Comics');
INSERT INTO genre (genre_name) VALUES ('Computer Science');
INSERT INTO genre (genre_name) VALUES ('Contemporary');
INSERT INTO genre (genre_name) VALUES ('Cookbook');
INSERT INTO genre (genre_name) VALUES ('Crime');
INSERT INTO genre (genre_name) VALUES ('Design');
INSERT INTO genre (genre_name) VALUES ('Dystopian');
INSERT INTO genre (genre_name) VALUES ('Economics');
INSERT INTO genre (genre_name) VALUES ('Education');
INSERT INTO genre (genre_name) VALUES ('Erotica');
INSERT INTO genre (genre_name) VALUES ('Essays');
INSERT INTO genre (genre_name) VALUES ('Fantasy');
INSERT INTO genre (genre_name) VALUES ('Feminism');
INSERT INTO genre (genre_name) VALUES ('Fiction');
INSERT INTO genre (genre_name) VALUES ('Food and Drink');
INSERT INTO genre (genre_name) VALUES ('Gender');
INSERT INTO genre (genre_name) VALUES ('Graphic Novel');
INSERT INTO genre (genre_name) VALUES ('Health');
INSERT INTO genre (genre_name) VALUES ('Historical');
INSERT INTO genre (genre_name) VALUES ('History');
INSERT INTO genre (genre_name) VALUES ('LGBTQIA+');
INSERT INTO genre (genre_name) VALUES ('Literary');
INSERT INTO genre (genre_name) VALUES ('Magical Realism');
INSERT INTO genre (genre_name) VALUES ('Manga');
INSERT INTO genre (genre_name) VALUES ('Mathematics');
INSERT INTO genre (genre_name) VALUES ('Memoir');
INSERT INTO genre (genre_name) VALUES ('Middle Grade');
INSERT INTO genre (genre_name) VALUES ('Music');
INSERT INTO genre (genre_name) VALUES ('Mystery');
INSERT INTO genre (genre_name) VALUES ('Nature');
INSERT INTO genre (genre_name) VALUES ('Nonfiction');
INSERT INTO genre (genre_name) VALUES ('Play');
INSERT INTO genre (genre_name) VALUES ('Poetry');
INSERT INTO genre (genre_name) VALUES ('Politics');
INSERT INTO genre (genre_name) VALUES ('Psychology');
INSERT INTO genre (genre_name) VALUES ('Race');
INSERT INTO genre (genre_name) VALUES ('Reference');
INSERT INTO genre (genre_name) VALUES ('Religion');
INSERT INTO genre (genre_name) VALUES ('Romance');
INSERT INTO genre (genre_name) VALUES ('Science');
INSERT INTO genre (genre_name) VALUES ('Science Fiction');
INSERT INTO genre (genre_name) VALUES ('Self Help');
INSERT INTO genre (genre_name) VALUES ('Short Stories');
INSERT INTO genre (genre_name) VALUES ('Sociology');
INSERT INTO genre (genre_name) VALUES ('Speculative Fiction');
INSERT INTO genre (genre_name) VALUES ('Sports');
INSERT INTO genre (genre_name) VALUES ('Technology');
INSERT INTO genre (genre_name) VALUES ('Thriller');
INSERT INTO genre (genre_name) VALUES ('Travel');
INSERT INTO genre (genre_name) VALUES ('True Crime');
INSERT INTO genre (genre_name) VALUES ('Video Games');
INSERT INTO genre (genre_name) VALUES ('Young Adult');
