-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 15:47:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema read_stat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema read_stat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `read_stat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `read_stat` ;

-- -----------------------------------------------------
-- Table `read_stat`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `read_stat`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `pages` INT NULL DEFAULT NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`book_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `read_stat`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `read_stat`.`genre` (
  `genre_name` VARCHAR(30) NOT NULL,
  UNIQUE INDEX `name` (`genre_name` ASC) VISIBLE,
  PRIMARY KEY (`genre_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `read_stat`.`user_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `read_stat`.`user_` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `read_stat`.`reading_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `read_stat`.`reading_session` (
  `username` VARCHAR(50) NOT NULL,
  `book_id` INT NOT NULL,
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `date_started` TIMESTAMP NULL,
  `date_finished` TIMESTAMP NULL,
  `rating` DECIMAL NULL,
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  PRIMARY KEY (`session_id`),
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC) VISIBLE,
  CONSTRAINT `user_to_books_read_ibfk_1`
    FOREIGN KEY (`username`)
    REFERENCES `read_stat`.`user_` (`username`),
  CONSTRAINT `user_to_books_read_ibfk_2`
    FOREIGN KEY (`book_id`)
    REFERENCES `read_stat`.`book` (`book_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `read_stat`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `read_stat`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `read_stat`.`author_to_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `read_stat`.`author_to_book` (
  `author_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`author_id`, `book_id`),
  INDEX `fk_author_has_book_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_author_has_book_author1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_author_has_book_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `read_stat`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_has_book_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `read_stat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `read_stat`.`book_to_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `read_stat`.`book_to_genre` (
  `book_id` INT NOT NULL,
  `genre_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`book_id`, `genre_name`),
  INDEX `fk_book_has_genre_genre1_idx` (`genre_name` ASC) VISIBLE,
  INDEX `fk_book_has_genre_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_has_genre_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `read_stat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_genre_genre1`
    FOREIGN KEY (`genre_name`)
    REFERENCES `read_stat`.`genre` (`genre_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
